node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    //def mvn = tool 'man';
    withSonarQubeEnv() {
      sh "/usr/local/Cellar/maven/3.8.6/libexec//bin/mvn clean verify sonar:sonar -Dsonar.projectKey=wechat"
    }
  }
}
